"""create team entitlement foundation

Revision ID: 41751533fa19
Revises: 543a25ffedf2
Create Date: 2026-08-07 10:57:27.527598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41751533fa19'
down_revision: Union[str, Sequence[str], None] = '543a25ffedf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_entitlements',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plan_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('allow_runtime_execution', sa.Boolean(), nullable=False),
    sa.Column('allow_paid_provider_usage', sa.Boolean(), nullable=False),
    sa.Column('allow_staging_deployments', sa.Boolean(), nullable=False),
    sa.Column('allow_production_deployments', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_entitlements_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_entitlements'))
    )
    op.create_index(op.f('ix_team_entitlements_team_id'), 'team_entitlements', ['team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_entitlements_team_id'), table_name='team_entitlements')
    op.drop_table('team_entitlements')
    # ### end Alembic commands ###
