"""create deployment foundation

Revision ID: 543a25ffedf2
Revises: fcf872c6390b
Create Date: 2026-08-05 09:09:53.237288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543a25ffedf2'
down_revision: Union[str, Sequence[str], None] = 'fcf872c6390b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('agent_version_id', sa.Uuid(), nullable=False),
    sa.Column('environment', sa.Enum('development', 'staging', 'production', name='deployment_environment', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('strategy', sa.Enum('rolling', 'canary', 'blue_green', name='deployment_strategy', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('requested', 'pending_approval', 'approved', 'deploying', 'running', 'failed', 'terminated', name='deployment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_deployments_agent_version_id_agent_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_deployments_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    op.create_index(op.f('ix_deployments_agent_version_id'), 'deployments', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_deployments_requested_by_user_id'), 'deployments', ['requested_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_requested_by_user_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_agent_version_id'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
