"""add team workspace ownership

Revision ID: b15bfa72b80d
Revises: 41751533fa19
Create Date: 2026-08-07 11:44:01.335999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15bfa72b80d'
down_revision: Union[str, Sequence[str], None] = '41751533fa19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_teams_created_by_user_id'), 'teams', ['created_by_user_id'], unique=False)
    op.create_foreign_key(op.f('fk_teams_created_by_user_id_users'), 'teams', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teams_created_by_user_id_users'), 'teams', type_='foreignkey')
    op.drop_index(op.f('ix_teams_created_by_user_id'), table_name='teams')
    op.drop_column('teams', 'created_by_user_id')
    # ### end Alembic commands ###
